# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build Test (manual)

on:
  workflow_dispatch:
    inputs:
      target_framework:
        type: choice
        required: true
        options:
          - "net6.0"
          - "net7.0"
          - "net8.0"
          - "net9.0"

jobs:
  build_and_test:
    name: Build & Test (${{ github.event.inputs.target_framework }})
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          7.0.x
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -f ${{ github.event.inputs.target_framework }}
    - name: Test
      run: dotnet test --no-build --verbosity normal -f ${{ github.event.inputs.target_framework }}
